# Production Docker Compose for EduHub (expects external Postgres via DATABASE_URL).
services:
  app:
    build: .
    image: eduhub-app:prod
    env_file: .env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
