// Centralized audit constants keep action/entity strings stable across writes + filters.
export const AUDIT_ACTIONS = {
  PARENT_LOGIN_SUCCEEDED: "PARENT_LOGIN_SUCCEEDED",
  PARENT_LOGIN_FAILED: "PARENT_LOGIN_FAILED",
  PARENT_LOGIN_THROTTLED: "PARENT_LOGIN_THROTTLED",
  PARENT_ACCESS_CODE_RESET: "PARENT_ACCESS_CODE_RESET",
  ABSENCE_REQUEST_CREATED: "ABSENCE_REQUEST_CREATED",
  ABSENCE_REQUEST_WITHDRAWN: "ABSENCE_REQUEST_WITHDRAWN",
  ABSENCE_REQUEST_RESUBMITTED: "ABSENCE_REQUEST_RESUBMITTED",
  ABSENCE_REQUEST_RESOLVED: "ABSENCE_REQUEST_RESOLVED",
  ATTENDANCE_PARENT_VISIBLE_NOTE_UPDATED:
    "ATTENDANCE_PARENT_VISIBLE_NOTE_UPDATED",
} as const;

// Entity types are intentionally minimal and filter-friendly for admin audit queries.
export const AUDIT_ENTITY_TYPES = {
  ACCESS_CODE: "ACCESS_CODE",
  REQUEST: "REQUEST",
  ATTENDANCE: "ATTENDANCE",
  SESSION: "SESSION",
  STUDENT: "STUDENT",
} as const;

// Auth-related actions are grouped for category filtering on admin audit endpoints.
export const AUDIT_AUTH_ACTIONS = [
  AUDIT_ACTIONS.PARENT_LOGIN_SUCCEEDED,
  AUDIT_ACTIONS.PARENT_LOGIN_FAILED,
  AUDIT_ACTIONS.PARENT_LOGIN_THROTTLED,
  AUDIT_ACTIONS.PARENT_ACCESS_CODE_RESET,
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
